

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: chain-listener_project-service_stats-save_pg
    topic: chain-listener_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: chain-listener_project-service_stats-save_cg
server:
  port: 9898
